# Generated by Django 3.2.7 on 2021-09-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('User ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=128)),
                ('Mail address', models.CharField(max_length=150)),
            ],
        ),
    ]
