# Generated by Django 3.2.7 on 2021-09-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webappgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accounts',
            new_name='account',
        ),
    ]
