# Generated by Django 3.2.7 on 2021-09-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webappgame', '0003_auto_20210918_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
        migrations.RemoveField(
            model_name='moonorbit',
            name='orbitof',
        ),
        migrations.DeleteModel(
            name='moontemplate',
        ),
        migrations.RemoveField(
            model_name='planetorbit',
            name='orbitof',
        ),
        migrations.DeleteModel(
            name='planettemplate',
        ),
        migrations.DeleteModel(
            name='solarsystem',
        ),
        migrations.DeleteModel(
            name='moon',
        ),
        migrations.DeleteModel(
            name='moonorbit',
        ),
        migrations.DeleteModel(
            name='planet',
        ),
        migrations.DeleteModel(
            name='planetorbit',
        ),
    ]
