# Generated by Django 3.2.7 on 2021-09-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webappgame', '0004_auto_20210918_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('User ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=128)),
                ('Mail address', models.CharField(max_length=150)),
                ('Premium member', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moon name', models.CharField(max_length=32, null=True)),
                ('Delta Temperature', models.IntegerField()),
                ('Moon size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='moontemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max temperature', models.IntegerField()),
                ('Min temperature', models.IntegerField()),
                ('Max size', models.IntegerField()),
                ('Min size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Planet name', models.CharField(max_length=32, null=True)),
                ('Delta Temperature', models.IntegerField()),
                ('Planet size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='planettemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max temperature', models.IntegerField()),
                ('Min temperature', models.IntegerField()),
                ('Max size', models.IntegerField()),
                ('Min size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='solarsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orbits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='planetorbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Planet orbit size', models.IntegerField()),
                ('orbitof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webappgame.planet')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='orbitof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webappgame.solarsystem'),
        ),
        migrations.CreateModel(
            name='moonorbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moon orbit size', models.IntegerField()),
                ('orbitof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webappgame.moon')),
            ],
        ),
        migrations.AddField(
            model_name='moon',
            name='orbitof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webappgame.planet'),
        ),
    ]
